# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 10:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostbody', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=32, unique=True)),
                ('remark', models.TextField(default='Null', max_length=1024)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=32, unique=True, verbose_name='\u5b9e\u4f8bID')),
                ('custom_name', models.CharField(max_length=32, verbose_name='\u81ea\u5b9a\u4e49\u540d\u79f0')),
                ('region', models.CharField(max_length=32, verbose_name='Region\u540d\u79f0')),
                ('region_part', models.CharField(max_length=32, verbose_name='\u6240\u5728\u53ef\u7528\u533a')),
                ('ip_public', models.GenericIPAddressField(unique=True, verbose_name='\u516c\u7f51IP')),
                ('ip_private', models.GenericIPAddressField(unique=True, verbose_name='\u5185\u7f51IP')),
                ('cpu_num', models.IntegerField(verbose_name='CPU')),
                ('memory', models.IntegerField(verbose_name='\u5185\u5b58')),
                ('pay_type', models.CharField(max_length=32, verbose_name='\u4ed8\u8d39\u7c7b\u578b')),
                ('net_type', models.CharField(max_length=32, verbose_name='\u7f51\u7edc\u7c7b\u578b')),
                ('bandwidth', models.IntegerField(verbose_name='\u5e26\u5bbd')),
                ('remark', models.TextField(default='Null', max_length=1024, verbose_name='\u6807\u7b7e')),
                ('group', models.ManyToManyField(to='hostbody.GroupInfo')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
