# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hostbody', '0003_auto_20170111_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfo',
            name='creation_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=32, verbose_name='\u521b\u5efa\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='expired_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=32, verbose_name='\u8fc7\u671f\u65f6\u95f4'),
            preserve_default=False,
        ),
    ]
