# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostbody', '0004_auto_20170112_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostinfo',
            name='group',
        ),
        migrations.AddField(
            model_name='groupinfo',
            name='host',
            field=models.ManyToManyField(to='hostbody.HostInfo'),
        ),
    ]
