# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostbody', '0005_auto_20170113_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinfo',
            name='host',
            field=models.ManyToManyField(blank=True, to='hostbody.HostInfo'),
        ),
    ]
